name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
    
    - name: Configure PDM
      run: |
        pdm config python.use_venv false
    
    - name: Install dependencies
      run: |
        pdm install
    
    - name: Debug environment
      run: |
        # Create directory for tests
        mkdir -p "$(pdm run python -c 'import appdirs; print(appdirs.user_data_dir("echomorse", "echomorse"))')/audio"
        
        # Debug voice discovery
        echo "Audio directories:"
        pdm run python -c "from echomorse.utils.voice_manager import USER_AUDIO_DIR, PACKAGE_AUDIO_DIR; print(f'User audio dir: {USER_AUDIO_DIR}'); print(f'Package audio dir: {PACKAGE_AUDIO_DIR}')"
        
        echo "Available voices:"
        pdm run python -c "from echomorse.utils.voice_manager import list_available_voices; print(list_available_voices())"
    
    - name: Run tests with coverage
      run: |
        pdm run pytest --cov=src/echomorse tests/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false